server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name:
      starter-redis-cache

  datasource:
    url: jdbc:postgresql://${DB_URI:localhost}:${DB_PORT:5432}/postgres
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      enabled: true